language: cpp

os:
  - linux

compiler:
  - g++

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - cmake -G "Unix Makefiles"

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"
  
script: make
